// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registration.proto

package com.tylerlowrey.grpc.device.registration;

public final class DeviceRegistrationProto {
  private DeviceRegistrationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code device.registration.RegistrationStatusCode}
   */
  public enum RegistrationStatusCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FAILED = 0;</code>
     */
    FAILED(0),
    /**
     * <code>SUCCESSFUL = 1;</code>
     */
    SUCCESSFUL(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>FAILED = 0;</code>
     */
    public static final int FAILED_VALUE = 0;
    /**
     * <code>SUCCESSFUL = 1;</code>
     */
    public static final int SUCCESSFUL_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RegistrationStatusCode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static RegistrationStatusCode forNumber(int value) {
      switch (value) {
        case 0: return FAILED;
        case 1: return SUCCESSFUL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RegistrationStatusCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RegistrationStatusCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RegistrationStatusCode>() {
            public RegistrationStatusCode findValueByNumber(int number) {
              return RegistrationStatusCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final RegistrationStatusCode[] VALUES = values();

    public static RegistrationStatusCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RegistrationStatusCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:device.registration.RegistrationStatusCode)
  }

  public interface RegistrationRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:device.registration.RegistrationRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string deviceAddress = 1;</code>
     * @return The deviceAddress.
     */
    java.lang.String getDeviceAddress();
    /**
     * <code>string deviceAddress = 1;</code>
     * @return The bytes for deviceAddress.
     */
    com.google.protobuf.ByteString
        getDeviceAddressBytes();
  }
  /**
   * Protobuf type {@code device.registration.RegistrationRequest}
   */
  public static final class RegistrationRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:device.registration.RegistrationRequest)
      RegistrationRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RegistrationRequest.newBuilder() to construct.
    private RegistrationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RegistrationRequest() {
      deviceAddress_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RegistrationRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RegistrationRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceAddress_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.internal_static_device_registration_RegistrationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.internal_static_device_registration_RegistrationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest.class, com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest.Builder.class);
    }

    public static final int DEVICEADDRESS_FIELD_NUMBER = 1;
    private volatile java.lang.Object deviceAddress_;
    /**
     * <code>string deviceAddress = 1;</code>
     * @return The deviceAddress.
     */
    @java.lang.Override
    public java.lang.String getDeviceAddress() {
      java.lang.Object ref = deviceAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceAddress_ = s;
        return s;
      }
    }
    /**
     * <code>string deviceAddress = 1;</code>
     * @return The bytes for deviceAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceAddressBytes() {
      java.lang.Object ref = deviceAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDeviceAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, deviceAddress_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDeviceAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, deviceAddress_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest)) {
        return super.equals(obj);
      }
      com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest other = (com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest) obj;

      if (!getDeviceAddress()
          .equals(other.getDeviceAddress())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICEADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceAddress().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code device.registration.RegistrationRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:device.registration.RegistrationRequest)
        com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.internal_static_device_registration_RegistrationRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.internal_static_device_registration_RegistrationRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest.class, com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest.Builder.class);
      }

      // Construct using com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        deviceAddress_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.internal_static_device_registration_RegistrationRequest_descriptor;
      }

      @java.lang.Override
      public com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest getDefaultInstanceForType() {
        return com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest build() {
        com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest buildPartial() {
        com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest result = new com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest(this);
        result.deviceAddress_ = deviceAddress_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest) {
          return mergeFrom((com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest other) {
        if (other == com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest.getDefaultInstance()) return this;
        if (!other.getDeviceAddress().isEmpty()) {
          deviceAddress_ = other.deviceAddress_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object deviceAddress_ = "";
      /**
       * <code>string deviceAddress = 1;</code>
       * @return The deviceAddress.
       */
      public java.lang.String getDeviceAddress() {
        java.lang.Object ref = deviceAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string deviceAddress = 1;</code>
       * @return The bytes for deviceAddress.
       */
      public com.google.protobuf.ByteString
          getDeviceAddressBytes() {
        java.lang.Object ref = deviceAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string deviceAddress = 1;</code>
       * @param value The deviceAddress to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string deviceAddress = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceAddress() {
        
        deviceAddress_ = getDefaultInstance().getDeviceAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string deviceAddress = 1;</code>
       * @param value The bytes for deviceAddress to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceAddress_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:device.registration.RegistrationRequest)
    }

    // @@protoc_insertion_point(class_scope:device.registration.RegistrationRequest)
    private static final com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest();
    }

    public static com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RegistrationRequest>
        PARSER = new com.google.protobuf.AbstractParser<RegistrationRequest>() {
      @java.lang.Override
      public RegistrationRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RegistrationRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RegistrationRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RegistrationRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RegistrationResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:device.registration.RegistrationResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.device.registration.RegistrationStatusCode statusCode = 1;</code>
     * @return The enum numeric value on the wire for statusCode.
     */
    int getStatusCodeValue();
    /**
     * <code>.device.registration.RegistrationStatusCode statusCode = 1;</code>
     * @return The statusCode.
     */
    com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationStatusCode getStatusCode();
  }
  /**
   * Protobuf type {@code device.registration.RegistrationResult}
   */
  public static final class RegistrationResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:device.registration.RegistrationResult)
      RegistrationResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RegistrationResult.newBuilder() to construct.
    private RegistrationResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RegistrationResult() {
      statusCode_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RegistrationResult();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RegistrationResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              statusCode_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.internal_static_device_registration_RegistrationResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.internal_static_device_registration_RegistrationResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult.class, com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult.Builder.class);
    }

    public static final int STATUSCODE_FIELD_NUMBER = 1;
    private int statusCode_;
    /**
     * <code>.device.registration.RegistrationStatusCode statusCode = 1;</code>
     * @return The enum numeric value on the wire for statusCode.
     */
    @java.lang.Override public int getStatusCodeValue() {
      return statusCode_;
    }
    /**
     * <code>.device.registration.RegistrationStatusCode statusCode = 1;</code>
     * @return The statusCode.
     */
    @java.lang.Override public com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationStatusCode getStatusCode() {
      @SuppressWarnings("deprecation")
      com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationStatusCode result = com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationStatusCode.valueOf(statusCode_);
      return result == null ? com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationStatusCode.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (statusCode_ != com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationStatusCode.FAILED.getNumber()) {
        output.writeEnum(1, statusCode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (statusCode_ != com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationStatusCode.FAILED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, statusCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult)) {
        return super.equals(obj);
      }
      com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult other = (com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult) obj;

      if (statusCode_ != other.statusCode_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUSCODE_FIELD_NUMBER;
      hash = (53 * hash) + statusCode_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code device.registration.RegistrationResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:device.registration.RegistrationResult)
        com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.internal_static_device_registration_RegistrationResult_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.internal_static_device_registration_RegistrationResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult.class, com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult.Builder.class);
      }

      // Construct using com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        statusCode_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.internal_static_device_registration_RegistrationResult_descriptor;
      }

      @java.lang.Override
      public com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult getDefaultInstanceForType() {
        return com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult.getDefaultInstance();
      }

      @java.lang.Override
      public com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult build() {
        com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult buildPartial() {
        com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult result = new com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult(this);
        result.statusCode_ = statusCode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult) {
          return mergeFrom((com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult other) {
        if (other == com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult.getDefaultInstance()) return this;
        if (other.statusCode_ != 0) {
          setStatusCodeValue(other.getStatusCodeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int statusCode_ = 0;
      /**
       * <code>.device.registration.RegistrationStatusCode statusCode = 1;</code>
       * @return The enum numeric value on the wire for statusCode.
       */
      @java.lang.Override public int getStatusCodeValue() {
        return statusCode_;
      }
      /**
       * <code>.device.registration.RegistrationStatusCode statusCode = 1;</code>
       * @param value The enum numeric value on the wire for statusCode to set.
       * @return This builder for chaining.
       */
      public Builder setStatusCodeValue(int value) {
        
        statusCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.device.registration.RegistrationStatusCode statusCode = 1;</code>
       * @return The statusCode.
       */
      @java.lang.Override
      public com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationStatusCode getStatusCode() {
        @SuppressWarnings("deprecation")
        com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationStatusCode result = com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationStatusCode.valueOf(statusCode_);
        return result == null ? com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationStatusCode.UNRECOGNIZED : result;
      }
      /**
       * <code>.device.registration.RegistrationStatusCode statusCode = 1;</code>
       * @param value The statusCode to set.
       * @return This builder for chaining.
       */
      public Builder setStatusCode(com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationStatusCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        statusCode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.device.registration.RegistrationStatusCode statusCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatusCode() {
        
        statusCode_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:device.registration.RegistrationResult)
    }

    // @@protoc_insertion_point(class_scope:device.registration.RegistrationResult)
    private static final com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult();
    }

    public static com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RegistrationResult>
        PARSER = new com.google.protobuf.AbstractParser<RegistrationResult>() {
      @java.lang.Override
      public RegistrationResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RegistrationResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RegistrationResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RegistrationResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tylerlowrey.grpc.device.registration.DeviceRegistrationProto.RegistrationResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_device_registration_RegistrationRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_device_registration_RegistrationRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_device_registration_RegistrationResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_device_registration_RegistrationResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022registration.proto\022\023device.registratio" +
      "n\",\n\023RegistrationRequest\022\025\n\rdeviceAddres" +
      "s\030\001 \001(\t\"U\n\022RegistrationResult\022?\n\nstatusC" +
      "ode\030\001 \001(\0162+.device.registration.Registra" +
      "tionStatusCode*4\n\026RegistrationStatusCode" +
      "\022\n\n\006FAILED\020\000\022\016\n\nSUCCESSFUL\020\0012p\n\023Registra" +
      "tionService\022Y\n\004Send\022(.device.registratio" +
      "n.RegistrationRequest\032\'.device.registrat" +
      "ion.RegistrationResultBC\n(com.tylerlowre" +
      "y.grpc.device.registrationB\027DeviceRegist" +
      "rationProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_device_registration_RegistrationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_device_registration_RegistrationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_device_registration_RegistrationRequest_descriptor,
        new java.lang.String[] { "DeviceAddress", });
    internal_static_device_registration_RegistrationResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_device_registration_RegistrationResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_device_registration_RegistrationResult_descriptor,
        new java.lang.String[] { "StatusCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
