// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: devicedata.proto

package com.tylerlowrey.grpc.device.data;

public final class DataCollectionProto {
  private DataCollectionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataPointOrBuilder extends
      // @@protoc_insertion_point(interface_extends:device.data.DataPoint)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string datatypes = 1;</code>
     * @return A list containing the datatypes.
     */
    java.util.List<java.lang.String>
        getDatatypesList();
    /**
     * <code>repeated string datatypes = 1;</code>
     * @return The count of datatypes.
     */
    int getDatatypesCount();
    /**
     * <code>repeated string datatypes = 1;</code>
     * @param index The index of the element to return.
     * @return The datatypes at the given index.
     */
    java.lang.String getDatatypes(int index);
    /**
     * <code>repeated string datatypes = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the datatypes at the given index.
     */
    com.google.protobuf.ByteString
        getDatatypesBytes(int index);

    /**
     * <code>map&lt;string, string&gt; values = 2;</code>
     */
    int getValuesCount();
    /**
     * <code>map&lt;string, string&gt; values = 2;</code>
     */
    boolean containsValues(
        java.lang.String key);
    /**
     * Use {@link #getValuesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getValues();
    /**
     * <code>map&lt;string, string&gt; values = 2;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getValuesMap();
    /**
     * <code>map&lt;string, string&gt; values = 2;</code>
     */

    java.lang.String getValuesOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; values = 2;</code>
     */

    java.lang.String getValuesOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code device.data.DataPoint}
   */
  public static final class DataPoint extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:device.data.DataPoint)
      DataPointOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataPoint.newBuilder() to construct.
    private DataPoint(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataPoint() {
      datatypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DataPoint();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DataPoint(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                datatypes_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              datatypes_.add(s);
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                values_ = com.google.protobuf.MapField.newMapField(
                    ValuesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              values__ = input.readMessage(
                  ValuesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              values_.getMutableMap().put(
                  values__.getKey(), values__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          datatypes_ = datatypes_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tylerlowrey.grpc.device.data.DataCollectionProto.internal_static_device_data_DataPoint_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetValues();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tylerlowrey.grpc.device.data.DataCollectionProto.internal_static_device_data_DataPoint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint.class, com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint.Builder.class);
    }

    public static final int DATATYPES_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList datatypes_;
    /**
     * <code>repeated string datatypes = 1;</code>
     * @return A list containing the datatypes.
     */
    public com.google.protobuf.ProtocolStringList
        getDatatypesList() {
      return datatypes_;
    }
    /**
     * <code>repeated string datatypes = 1;</code>
     * @return The count of datatypes.
     */
    public int getDatatypesCount() {
      return datatypes_.size();
    }
    /**
     * <code>repeated string datatypes = 1;</code>
     * @param index The index of the element to return.
     * @return The datatypes at the given index.
     */
    public java.lang.String getDatatypes(int index) {
      return datatypes_.get(index);
    }
    /**
     * <code>repeated string datatypes = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the datatypes at the given index.
     */
    public com.google.protobuf.ByteString
        getDatatypesBytes(int index) {
      return datatypes_.getByteString(index);
    }

    public static final int VALUES_FIELD_NUMBER = 2;
    private static final class ValuesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.tylerlowrey.grpc.device.data.DataCollectionProto.internal_static_device_data_DataPoint_ValuesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> values_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetValues() {
      if (values_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ValuesDefaultEntryHolder.defaultEntry);
      }
      return values_;
    }

    public int getValuesCount() {
      return internalGetValues().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; values = 2;</code>
     */

    @java.lang.Override
    public boolean containsValues(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetValues().getMap().containsKey(key);
    }
    /**
     * Use {@link #getValuesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getValues() {
      return getValuesMap();
    }
    /**
     * <code>map&lt;string, string&gt; values = 2;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getValuesMap() {
      return internalGetValues().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; values = 2;</code>
     */
    @java.lang.Override

    public java.lang.String getValuesOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetValues().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; values = 2;</code>
     */
    @java.lang.Override

    public java.lang.String getValuesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetValues().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < datatypes_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, datatypes_.getRaw(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetValues(),
          ValuesDefaultEntryHolder.defaultEntry,
          2);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < datatypes_.size(); i++) {
          dataSize += computeStringSizeNoTag(datatypes_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getDatatypesList().size();
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetValues().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        values__ = ValuesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, values__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint)) {
        return super.equals(obj);
      }
      com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint other = (com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint) obj;

      if (!getDatatypesList()
          .equals(other.getDatatypesList())) return false;
      if (!internalGetValues().equals(
          other.internalGetValues())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDatatypesCount() > 0) {
        hash = (37 * hash) + DATATYPES_FIELD_NUMBER;
        hash = (53 * hash) + getDatatypesList().hashCode();
      }
      if (!internalGetValues().getMap().isEmpty()) {
        hash = (37 * hash) + VALUES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetValues().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code device.data.DataPoint}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:device.data.DataPoint)
        com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPointOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tylerlowrey.grpc.device.data.DataCollectionProto.internal_static_device_data_DataPoint_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetValues();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableValues();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tylerlowrey.grpc.device.data.DataCollectionProto.internal_static_device_data_DataPoint_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint.class, com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint.Builder.class);
      }

      // Construct using com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        datatypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        internalGetMutableValues().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tylerlowrey.grpc.device.data.DataCollectionProto.internal_static_device_data_DataPoint_descriptor;
      }

      @java.lang.Override
      public com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint getDefaultInstanceForType() {
        return com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint.getDefaultInstance();
      }

      @java.lang.Override
      public com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint build() {
        com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint buildPartial() {
        com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint result = new com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          datatypes_ = datatypes_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.datatypes_ = datatypes_;
        result.values_ = internalGetValues();
        result.values_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint) {
          return mergeFrom((com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint other) {
        if (other == com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint.getDefaultInstance()) return this;
        if (!other.datatypes_.isEmpty()) {
          if (datatypes_.isEmpty()) {
            datatypes_ = other.datatypes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDatatypesIsMutable();
            datatypes_.addAll(other.datatypes_);
          }
          onChanged();
        }
        internalGetMutableValues().mergeFrom(
            other.internalGetValues());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList datatypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureDatatypesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          datatypes_ = new com.google.protobuf.LazyStringArrayList(datatypes_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string datatypes = 1;</code>
       * @return A list containing the datatypes.
       */
      public com.google.protobuf.ProtocolStringList
          getDatatypesList() {
        return datatypes_.getUnmodifiableView();
      }
      /**
       * <code>repeated string datatypes = 1;</code>
       * @return The count of datatypes.
       */
      public int getDatatypesCount() {
        return datatypes_.size();
      }
      /**
       * <code>repeated string datatypes = 1;</code>
       * @param index The index of the element to return.
       * @return The datatypes at the given index.
       */
      public java.lang.String getDatatypes(int index) {
        return datatypes_.get(index);
      }
      /**
       * <code>repeated string datatypes = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the datatypes at the given index.
       */
      public com.google.protobuf.ByteString
          getDatatypesBytes(int index) {
        return datatypes_.getByteString(index);
      }
      /**
       * <code>repeated string datatypes = 1;</code>
       * @param index The index to set the value at.
       * @param value The datatypes to set.
       * @return This builder for chaining.
       */
      public Builder setDatatypes(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDatatypesIsMutable();
        datatypes_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string datatypes = 1;</code>
       * @param value The datatypes to add.
       * @return This builder for chaining.
       */
      public Builder addDatatypes(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDatatypesIsMutable();
        datatypes_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string datatypes = 1;</code>
       * @param values The datatypes to add.
       * @return This builder for chaining.
       */
      public Builder addAllDatatypes(
          java.lang.Iterable<java.lang.String> values) {
        ensureDatatypesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, datatypes_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string datatypes = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDatatypes() {
        datatypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string datatypes = 1;</code>
       * @param value The bytes of the datatypes to add.
       * @return This builder for chaining.
       */
      public Builder addDatatypesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureDatatypesIsMutable();
        datatypes_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> values_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetValues() {
        if (values_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ValuesDefaultEntryHolder.defaultEntry);
        }
        return values_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableValues() {
        onChanged();;
        if (values_ == null) {
          values_ = com.google.protobuf.MapField.newMapField(
              ValuesDefaultEntryHolder.defaultEntry);
        }
        if (!values_.isMutable()) {
          values_ = values_.copy();
        }
        return values_;
      }

      public int getValuesCount() {
        return internalGetValues().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; values = 2;</code>
       */

      @java.lang.Override
      public boolean containsValues(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetValues().getMap().containsKey(key);
      }
      /**
       * Use {@link #getValuesMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getValues() {
        return getValuesMap();
      }
      /**
       * <code>map&lt;string, string&gt; values = 2;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, java.lang.String> getValuesMap() {
        return internalGetValues().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; values = 2;</code>
       */
      @java.lang.Override

      public java.lang.String getValuesOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetValues().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; values = 2;</code>
       */
      @java.lang.Override

      public java.lang.String getValuesOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetValues().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearValues() {
        internalGetMutableValues().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; values = 2;</code>
       */

      public Builder removeValues(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableValues().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableValues() {
        return internalGetMutableValues().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; values = 2;</code>
       */
      public Builder putValues(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableValues().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; values = 2;</code>
       */

      public Builder putAllValues(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableValues().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:device.data.DataPoint)
    }

    // @@protoc_insertion_point(class_scope:device.data.DataPoint)
    private static final com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint();
    }

    public static com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataPoint>
        PARSER = new com.google.protobuf.AbstractParser<DataPoint>() {
      @java.lang.Override
      public DataPoint parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataPoint(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataPoint> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataPoint> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tylerlowrey.grpc.device.data.DataCollectionProto.DataPoint getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DataReceivedResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:device.data.DataReceivedResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.device.data.DataReceivedResponse.StatusCode statusCode = 1;</code>
     * @return The enum numeric value on the wire for statusCode.
     */
    int getStatusCodeValue();
    /**
     * <code>.device.data.DataReceivedResponse.StatusCode statusCode = 1;</code>
     * @return The statusCode.
     */
    com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse.StatusCode getStatusCode();
  }
  /**
   * Protobuf type {@code device.data.DataReceivedResponse}
   */
  public static final class DataReceivedResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:device.data.DataReceivedResponse)
      DataReceivedResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataReceivedResponse.newBuilder() to construct.
    private DataReceivedResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataReceivedResponse() {
      statusCode_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DataReceivedResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DataReceivedResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              statusCode_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tylerlowrey.grpc.device.data.DataCollectionProto.internal_static_device_data_DataReceivedResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tylerlowrey.grpc.device.data.DataCollectionProto.internal_static_device_data_DataReceivedResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse.class, com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse.Builder.class);
    }

    /**
     * Protobuf enum {@code device.data.DataReceivedResponse.StatusCode}
     */
    public enum StatusCode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SUCCESS = 0;</code>
       */
      SUCCESS(0),
      /**
       * <code>BAD_PAYLOAD = 1;</code>
       */
      BAD_PAYLOAD(1),
      /**
       * <code>DATATYPE_MISMATCH = 2;</code>
       */
      DATATYPE_MISMATCH(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>SUCCESS = 0;</code>
       */
      public static final int SUCCESS_VALUE = 0;
      /**
       * <code>BAD_PAYLOAD = 1;</code>
       */
      public static final int BAD_PAYLOAD_VALUE = 1;
      /**
       * <code>DATATYPE_MISMATCH = 2;</code>
       */
      public static final int DATATYPE_MISMATCH_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static StatusCode valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static StatusCode forNumber(int value) {
        switch (value) {
          case 0: return SUCCESS;
          case 1: return BAD_PAYLOAD;
          case 2: return DATATYPE_MISMATCH;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<StatusCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          StatusCode> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<StatusCode>() {
              public StatusCode findValueByNumber(int number) {
                return StatusCode.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final StatusCode[] VALUES = values();

      public static StatusCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private StatusCode(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:device.data.DataReceivedResponse.StatusCode)
    }

    public static final int STATUSCODE_FIELD_NUMBER = 1;
    private int statusCode_;
    /**
     * <code>.device.data.DataReceivedResponse.StatusCode statusCode = 1;</code>
     * @return The enum numeric value on the wire for statusCode.
     */
    @java.lang.Override public int getStatusCodeValue() {
      return statusCode_;
    }
    /**
     * <code>.device.data.DataReceivedResponse.StatusCode statusCode = 1;</code>
     * @return The statusCode.
     */
    @java.lang.Override public com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse.StatusCode getStatusCode() {
      @SuppressWarnings("deprecation")
      com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse.StatusCode result = com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse.StatusCode.valueOf(statusCode_);
      return result == null ? com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse.StatusCode.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (statusCode_ != com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse.StatusCode.SUCCESS.getNumber()) {
        output.writeEnum(1, statusCode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (statusCode_ != com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse.StatusCode.SUCCESS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, statusCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse)) {
        return super.equals(obj);
      }
      com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse other = (com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse) obj;

      if (statusCode_ != other.statusCode_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUSCODE_FIELD_NUMBER;
      hash = (53 * hash) + statusCode_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code device.data.DataReceivedResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:device.data.DataReceivedResponse)
        com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tylerlowrey.grpc.device.data.DataCollectionProto.internal_static_device_data_DataReceivedResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tylerlowrey.grpc.device.data.DataCollectionProto.internal_static_device_data_DataReceivedResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse.class, com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse.Builder.class);
      }

      // Construct using com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        statusCode_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tylerlowrey.grpc.device.data.DataCollectionProto.internal_static_device_data_DataReceivedResponse_descriptor;
      }

      @java.lang.Override
      public com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse getDefaultInstanceForType() {
        return com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse build() {
        com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse buildPartial() {
        com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse result = new com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse(this);
        result.statusCode_ = statusCode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse) {
          return mergeFrom((com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse other) {
        if (other == com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse.getDefaultInstance()) return this;
        if (other.statusCode_ != 0) {
          setStatusCodeValue(other.getStatusCodeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int statusCode_ = 0;
      /**
       * <code>.device.data.DataReceivedResponse.StatusCode statusCode = 1;</code>
       * @return The enum numeric value on the wire for statusCode.
       */
      @java.lang.Override public int getStatusCodeValue() {
        return statusCode_;
      }
      /**
       * <code>.device.data.DataReceivedResponse.StatusCode statusCode = 1;</code>
       * @param value The enum numeric value on the wire for statusCode to set.
       * @return This builder for chaining.
       */
      public Builder setStatusCodeValue(int value) {
        
        statusCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.device.data.DataReceivedResponse.StatusCode statusCode = 1;</code>
       * @return The statusCode.
       */
      @java.lang.Override
      public com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse.StatusCode getStatusCode() {
        @SuppressWarnings("deprecation")
        com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse.StatusCode result = com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse.StatusCode.valueOf(statusCode_);
        return result == null ? com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse.StatusCode.UNRECOGNIZED : result;
      }
      /**
       * <code>.device.data.DataReceivedResponse.StatusCode statusCode = 1;</code>
       * @param value The statusCode to set.
       * @return This builder for chaining.
       */
      public Builder setStatusCode(com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse.StatusCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        statusCode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.device.data.DataReceivedResponse.StatusCode statusCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatusCode() {
        
        statusCode_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:device.data.DataReceivedResponse)
    }

    // @@protoc_insertion_point(class_scope:device.data.DataReceivedResponse)
    private static final com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse();
    }

    public static com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataReceivedResponse>
        PARSER = new com.google.protobuf.AbstractParser<DataReceivedResponse>() {
      @java.lang.Override
      public DataReceivedResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataReceivedResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataReceivedResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataReceivedResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tylerlowrey.grpc.device.data.DataCollectionProto.DataReceivedResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_device_data_DataPoint_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_device_data_DataPoint_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_device_data_DataPoint_ValuesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_device_data_DataPoint_ValuesEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_device_data_DataReceivedResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_device_data_DataReceivedResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020devicedata.proto\022\013device.data\"\201\001\n\tData" +
      "Point\022\021\n\tdatatypes\030\001 \003(\t\0222\n\006values\030\002 \003(\013" +
      "2\".device.data.DataPoint.ValuesEntry\032-\n\013" +
      "ValuesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:" +
      "\0028\001\"\233\001\n\024DataReceivedResponse\022@\n\nstatusCo" +
      "de\030\001 \001(\0162,.device.data.DataReceivedRespo" +
      "nse.StatusCode\"A\n\nStatusCode\022\013\n\007SUCCESS\020" +
      "\000\022\017\n\013BAD_PAYLOAD\020\001\022\025\n\021DATATYPE_MISMATCH\020" +
      "\0022^\n\025DataCollectionService\022E\n\010sendData\022\026" +
      ".device.data.DataPoint\032!.device.data.Dat" +
      "aReceivedResponseB7\n com.tylerlowrey.grp" +
      "c.device.dataB\023DataCollectionProtob\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_device_data_DataPoint_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_device_data_DataPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_device_data_DataPoint_descriptor,
        new java.lang.String[] { "Datatypes", "Values", });
    internal_static_device_data_DataPoint_ValuesEntry_descriptor =
      internal_static_device_data_DataPoint_descriptor.getNestedTypes().get(0);
    internal_static_device_data_DataPoint_ValuesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_device_data_DataPoint_ValuesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_device_data_DataReceivedResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_device_data_DataReceivedResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_device_data_DataReceivedResponse_descriptor,
        new java.lang.String[] { "StatusCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
